version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "npm run build && npm run typeorm:migration:run &&
      npm run start:prod"
    volumes:
      - .:/app
    ports:
      - "5050:5050"
    environment:
      - PORT
      - MODE=DEV
      - RUN_MIGRATIONS=true
      - JWT_SECRET
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DATABASE=letevent_core
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5051:5432"
